/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wgtools_WgSubcommand */

#ifndef _Included_com_wgtools_WgSubcommand
#define _Included_com_wgtools_WgSubcommand
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wgtools_WgSubcommand
 * Method:    wgCommand
 * Signature: ([Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wgtools_WgSubcommand_wgCommand
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
